### Creates a new patient entity
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "John Doe billing account test",
  "email": "test_billing_acc@example.com",
  "address": "123 main street1",
  "dateOfBirth": "1995-09-09",
  "registeredDate": "2024-12-28"
}

###