### Creates a new patient entity
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "Unique man",
  "email": "unique@example.com",
  "address": "1231 main street1",
  "dateOfBirth": "1995-07-09",
  "registeredDate": "2024-10-28"
}

###